// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// svf_raycast_cpp
List svf_raycast_cpp(NumericMatrix coords, NumericVector obs_values, NumericVector observer_z, NumericVector directions_deg, NumericVector distances, double xmin, double ymax, double xres, double yres, int ncol, int nrow, bool return_raw_angles);
RcppExport SEXP _greenR_svf_raycast_cpp(SEXP coordsSEXP, SEXP obs_valuesSEXP, SEXP observer_zSEXP, SEXP directions_degSEXP, SEXP distancesSEXP, SEXP xminSEXP, SEXP ymaxSEXP, SEXP xresSEXP, SEXP yresSEXP, SEXP ncolSEXP, SEXP nrowSEXP, SEXP return_raw_anglesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs_values(obs_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observer_z(observer_zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type directions_deg(directions_degSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< double >::type xres(xresSEXP);
    Rcpp::traits::input_parameter< double >::type yres(yresSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< bool >::type return_raw_angles(return_raw_anglesSEXP);
    rcpp_result_gen = Rcpp::wrap(svf_raycast_cpp(coords, obs_values, observer_z, directions_deg, distances, xmin, ymax, xres, yres, ncol, nrow, return_raw_angles));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_greenR_svf_raycast_cpp", (DL_FUNC) &_greenR_svf_raycast_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_greenR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
