# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

svf_raycast_cpp <- function(coords, obs_values, observer_z, directions_deg, distances, xmin, ymax, xres, yres, ncol, nrow, return_raw_angles) {
    .Call(`_greenR_svf_raycast_cpp`, coords, obs_values, observer_z, directions_deg, distances, xmin, ymax, xres, yres, ncol, nrow, return_raw_angles)
}

